import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system';

export const pdfService = {
  /**
   * Generates a professional A4 PDF combining the captured Business Card and QR Card images.
   * @param {Object} profile - User profile
   * @param {string} businessCardUri - Local URI of captured Business Card
   * @param {string} qrCardUri - Local URI of captured QR Card
   * @returns {Promise<string>} Local URI of the generated PDF
   */
  generatePDF: async (profile, businessCardUri, qrCardUri) => {
    try {
      // Read images as Base64 to embed in HTML since local URIs might not render correctly in expo-print webview on all platforms
      const businessCardBase64 = await FileSystem.readAsStringAsync(businessCardUri, { encoding: FileSystem.EncodingType.Base64 });
      const qrCardBase64 = await FileSystem.readAsStringAsync(qrCardUri, { encoding: FileSystem.EncodingType.Base64 });

      const fullName = profile?.personal?.fullName || 'User';
      const jobTitle = profile?.personal?.jobTitle || '';
      const company = profile?.personal?.company || '';
      const mobile = profile?.contact?.mobile || '';
      const email = profile?.contact?.email || '';

      const html = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
              body {
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                margin: 0;
                padding: 40px;
                background-color: #FFFFFF;
                color: #333333;
                display: flex;
                flex-direction: column;
                align-items: center;
              }
              .header {
                text-align: center;
                margin-bottom: 40px;
              }
              .header h1 {
                margin: 0;
                font-size: 28px;
                color: #000000;
              }
              .header p {
                margin: 5px 0 0;
                font-size: 16px;
                color: #666666;
              }
              .card-container {
                margin-bottom: 40px;
                width: 100%;
                max-width: 400px;
                display: flex;
                flex-direction: column;
                align-items: center;
              }
              .card-image {
                width: 100%;
                height: auto;
                border-radius: 12px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.1);
                margin-bottom: 30px;
              }
              .qr-image {
                width: 60%;
                max-width: 250px;
                height: auto;
                border-radius: 12px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.1);
              }
              .contact-info {
                margin-top: 20px;
                text-align: center;
                font-size: 14px;
                line-height: 1.6;
              }
              .footer {
                margin-top: auto;
                padding-top: 40px;
                font-size: 10px;
                color: #999999;
                text-align: center;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>${fullName}</h1>
              ${jobTitle ? `<p>${jobTitle}${company ? ` at ${company}` : ''}</p>` : ''}
            </div>

            <div class="card-container">
              <img src="data:image/png;base64,${businessCardBase64}" class="card-image" />
              <img src="data:image/png;base64,${qrCardBase64}" class="qr-image" />
            </div>

            <div class="contact-info">
              ${mobile ? `<div>${mobile}</div>` : ''}
              ${email ? `<div>${email}</div>` : ''}
            </div>

            <div class="footer">
              Generated by CardSphere
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      return uri;
    } catch (error) {
      throw new Error(`Failed to generate PDF: ${error.message}`);
    }
  }
};
